=== DjordjeR/automatelife/automatelife/templates/languages/python/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "additionalProperties": true,
    "required": [
        "name",
        "structure",
        "gitignore",
        "commands"
    ],
    "properties": {
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "python"
            ]
        },
        "structure": {
            "$id": "#/properties/structure",
            "type": "array",
            "title": "The Structure Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "dir": [
                            "$projectName"
                        ],
                        "files": [
                            "__init__.py",
                            "core.py"
                        ]
                    },
                    {
                        "dir": "bin",
                        "files": [
                            "example.py"
                        ]
                    },
                    {
                        "dir": "tests"
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/structure/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": {},
                "examples": [
                    {
                        "dir": [
                            "$projectName"
                        ],
                        "files": [
                            "__init__.py",
                            "core.py"
                        ]
                    },
                    {
                        "dir": "bin",
                        "files": [
                            "example.py"
                        ]
                    },
                    {
                        "dir": "tests"
                    }
                ],
                "additionalProperties": true,
                "required": [
                    "dir"
                ],
                "properties": {
                    "dir": {
                        "$id": "#/properties/structure/items/properties/dir",
                        "type": [
                            "array",
                            "null"
                        ],
                        "title": "The Dir Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": [],
                        "examples": [
                            [
                                "$projectName"
                            ]
                        ],
                        "additionalItems": true,
                        "items": {
                            "$id": "#/properties/structure/items/properties/dir/items",
                            "type": "string",
                            "title": "The Items Schema",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "$projectName"
                            ],
                            "uniqueItems": true
                        }
                    },
                    "files": {
                        "$id": "#/properties/structure/items/properties/files",
                        "type": "array",
                        "title": "The Files Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": [],
                        "examples": [
                            [
                                "__init__.py",
                                "core.py"
                            ]
                        ],
                        "additionalItems": true,
                        "items": {
                            "$id": "#/properties/structure/items/properties/files/items",
                            "type": "string",
                            "title": "The Items Schema",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "__init__.py",
                                "core.py"
                            ],
                            "uniqueItems": true
                        }
                    }
                }
            }
        },
        "gitignore": {
            "$id": "#/properties/gitignore",
            "type": "array",
            "title": "The Gitignore Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    "python",
                    "visualstudiocode",
                    "pycharm"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/gitignore/items",
                "type": "string",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "python",
                    "visualstudiocode",
                    "pycharm"
                ],
                "uniqueItems": true
            }
        },
        "commands": {
            "$id": "#/properties/commands",
            "type": "array",
            "title": "The Commands Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    "git init"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/commands/items",
                "type": "string",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "git init"
                ]
            }
        }
    }
}

=== DjordjeR/automatelife/automatelife/templates/languages/python/python.json
{
  "$schema": ".\\schema.json",
  "name": "python",
  "structure": [
    {
      "dir": null,
      "files": ["setup.py", ".gitignore", "README.md"]
    },
    {
      "dir":  ["$projectName"],
      "files": ["__init__.py", "core.py"]
    },
    {
      "dir": ["bin"],
      "files": ["example.py"]
    },
    {
      "dir": ["tests"]
    },
    {
      "dir": ["docs"]
    }
  ],
  "gitignore": [
    "python",
    "visualstudiocode",
    "pycharm",
    "venv"
  ],
  "commands": [
    "git init"
  ]
}
